---
- name: Converge
  hosts: all
  gather_facts: yes

  vars:
    bash_configure_users:
      - name: root

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: yes
      when: ansible_os_family == 'Debian'

  roles:
    - role: chronicc.bash
