---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-centos:7}"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
