name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create ansible roles directory
        run: |
          mkdir -p ~/.ansible/roles

      - name: Create role symlink
        run: |
          ln -s $PWD ~/.ansible/roles/chronicc.bash

      - uses: pre-commit/action@v3.0.0
